FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /project

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    libpq-dev \
    curl \
    yq \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip
RUN pip install uv

RUN pip install --no-cache-dir "sqlmesh[postgres]" dlt ==1.14.1

COPY ./template .
COPY ./macros /project/

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
