FROM apache/superset:GHA-dev-16357708668

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="/app/pythonpath"
ENV SUPERSET_SECRET_KEY="aZ1x9vqfK2w+G+dwiXm16BnyhsJXgsmwuIiLNqKDRI/8x7axAscKc7Dg"
ENV FLASK_APP=superset

USER root
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    default-libmysqlclient-dev \
    curl \
    git \
    sed \
    gcc \
    yq \
    libpq-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip
    
RUN pip install psycopg2
COPY superset_config.py /app/pythonpath/

EXPOSE 8088

CMD /bin/bash -c "\
    superset db upgrade && \
    superset fab create-admin \
        --username \${ADMIN_USERNAME:-admin} \
        --firstname \${ADMIN_FIRSTNAME:-Admin} \
        --lastname \${ADMIN_LASTNAME:-User} \
        --email \${ADMIN_EMAIL:-admin@example.com} \
        --password \${ADMIN_PASSWORD:-admin123} && \
    superset init && \
    superset run -h 0.0.0.0 -p 8088"