FROM n8nio/n8n:1.102.4

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=http
ENV NODE_ENV=production

RUN mkdir -p /home/node/.n8n

WORKDIR /home/node
COPY ./n8nTemplate/transformationegent.json /home/node/workflows/transformationegent.json
COPY ./n8nTemplate/credentials.json /home/node/credentials/credentials.json

EXPOSE 5678
